export interface Association{
        id?: number; // optional because it's generated by the backend
        name?: string;
        email: string;
        password: string;
        phoneNumber?: string;
        address?: string;
        description?: string;
        isValidated: boolean;
        creationDate?: string; // LocalDateTime is typically represented as ISO string in JSON
        profileImageUrl?: string;
  }

  
  