export enum CategoryA {
    DISCOVERY_AND_CULTURE = "DISCOVERY_AND_CULTURE",
    NATURE_AND_ADVENTURE = "NATURE_AND_ADVENTURE",
    WELLNESS_AND_RELAXATION = "WELLNESS_AND_RELAXATION",
    ENTERTAINMENT = "ENTERTAINMENT"
  }