# Étape 1 : Build Angular
FROM node:18-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# Étape 2 : Serve Angular via NGINX
FROM nginx:alpine
COPY --from=build /app/dist/nom-de-ton-app /usr/share/nginx/html

# Ajout d'un fichier de config nginx pour gérer le proxy
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
